jango_ui/blogs/urls.py
from django.urls import path
from . import views


app_name = 'blogs'


urlpatterns = [
    path('', views.home_page, name='home_page'),
    path('all', views.BlogsView.as_view(), name='blogs_list'),
    path('blog/<int:id>/', views.blog_view, name='blog'),
    path('Categories/<str:slug>/', views.category_view, name='category'),
    path('home_page', views.HomePageView.as_view(), name='home_page'),
    path('author/<str:author>/', views.author_viev, name='author_blogs'),
    path('user_home/', views.UserHomeView.as_view(), name='user_home'),
    path('add/', views.AddBlogFormView.as_view(), name='add_blog'),
    path('update/<str:slug>/', views.UpdateBlogFormView.as_view(), name='update_blog'),
    path('add_category/', views.AddCategoryFormView.as_view(), name='add_category')
]

jango_ui/django_project_ilya/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blogs.urls')),
    path('users/', include('users.urls')),
    *staticfiles_urlpatterns(),
    *static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
]

jango_ui/users/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path
from . import views


app_name = 'users'


urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout')
]

jango_ui/blogs/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils.text import slugify


class Category(models.Model):
    category = models.CharField(max_length=30)
    slug = models.SlugField(unique=True, allow_unicode=True, default=None, blank=True, null=True)

    def __str__(self):
        return str(self.category)

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        if not self.slug:
            self.slug = slugify(self.category)
        super().save(force_insert=False, force_update=False, using=None, update_fields=None)


class Blogs(models.Model):
    name = models.CharField(max_length=80)
    slug = models.SlugField(unique=True, allow_unicode=True, default=None, blank=True, null=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    text = models.TextField(blank=True)
    author = models.ForeignKey(User, on_delete=models.SET_NULL, default=None, null=True)
    date = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(default='blog.png', blank=True)

    def __str__(self):
        return f'{self.name} - {self.author} - {self.category} - {self.date}'

    def uniq_slug(self, slug):
        unique_slug = slug
        num = 1
        while Blogs.objects.filter(slug=unique_slug).exists():
            unique_slug = slug + f"_{num}"
            num+=1
        return unique_slug

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        if not self.slug:
            self.slug = self.uniq_slug(slugify(self.name))

        super().save(force_insert=False, force_update=False, using=None, update_fields=None)

    def get_absolute_url(self):
        return reverse('blogs:items', kwargs={'slug': self.slug})

jango_ui/users/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.models import User

jango_ui/blogs/forms.py
from django import forms
from . import models
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class BlogsForm(forms.ModelForm):
    class Meta:
        model = models.Blogs
        fields = ['name', 'category', 'text', 'image']


class RegisterForm(UserCreationForm):
    email = forms.EmailField(label="Email")
    fullname = forms.CharField(label="Full name")

    class Meta:
        model = User
        fields = ["username", "fullname", "email"]


class CategoryForm(forms.ModelForm):
    class Meta:
        model = models.Category
        fields = ['category']

jango_ui/users/forms.py
from django.forms import CharField, EmailField
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    email = EmailField(max_length=255)
    first_name = CharField(max_length=20)
    last_name = CharField(max_length=20)

    class Meta:
        model = User
        fields = ["username",
                  "first_name",
                  "last_name",
                  "email"]

jango_ui/blogs/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.shortcuts import render
from django.template.context_processors import request
from .models import Blogs, Category
from django.views.generic import ListView, DetailView, UpdateView, CreateView


def home_page(request):
    return render(request, 'blogs/home_page.html')


class BlogsView(ListView):
    model = Blogs
    template_name = 'blogs/all_blogs.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['url'] = "http://127.0.0.1:8123/api/all/"
        context['Name'] = "Все записи"
        return context


def blog_view(request, id):
    return render(request, 'blogs/blog.html',
                  context={'url': f"http://127.0.0.1:8123/api/blog/{id}/",
                           'Name': f"Blog-{id}"
                           })


def category_view(request, slug):
        return render(request, 'blogs/all_blogs.html',
              context={'url': f"http://127.0.0.1:8123/api/category/{slug}/",
                       'Name': slug
                      })


def author_viev(request, author):
        return render(request, 'blogs/all_blogs.html',
              context={'url': f"http://127.0.0.1:8123/api/user/{author}/",
                       'Name': author
                       })


class HomePageView(ListView):
    model = Blogs
    context_object_name = 'blogs'
    template_name = 'blogs/home_page.html'


class AddBlogFormView(LoginRequiredMixin, CreateView):
    template_name = 'blogs/add_blog.html'
    model = Blogs
    fields = ['name', 'category', 'text', 'image']

    def form_valid(self, form):
        new_blog = form.save(commit=False)
        new_blog.author = self.request.user
        return super().form_valid(form)


class UpdateBlogFormView(LoginRequiredMixin, UpdateView):
        template_name = 'blogs/update_blog.html'
        model = Blogs
        fields = ['name', 'category', 'text', 'image']

        def form_valid(self, form):
            if self.request.user.id == self.object.author.id:
                return super().form_valid(form)
            else:
                author = self.object.author
                return render(self.request, 'blogs/error.html', context={'author': author})


class UserHomeView(LoginRequiredMixin, ListView):
    template_name = 'blogs/user_home.html'
    model = Blogs

    def form_valid(self, form):
        new_blog = form.save(commit=False)
        new_blog.author = self.request.user
        return super().request


class AddCategoryFormView(LoginRequiredMixin, CreateView):
    template_name = 'blogs/add_category.html'
    model = Category
    fields = ['category']

    def form_valid(self, form):
        new_blog = form.save(commit=False)
        new_blog.author = self.request.user
        return super().form_valid(form)

jango_ui/django_project_ilya/views.py
from django.shortcuts import render

jango_ui/users/views.py
from django.contrib.auth.forms import AuthenticationForm
from django.shortcuts import render, redirect
from django.contrib.auth import login as auth_login, logout as auth_logout
from users.forms import SignUpForm


def signup(request):
    form = SignUpForm(request.POST)
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            return redirect('users:login')
    return render(request, 'users/signup.html', context={'form': form})


def login(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('blogs:user_home')
    form = AuthenticationForm()
    return render(request, 'users/login.html', context={'form': form})


def logout(request):
    auth_logout(request)
    return redirect('users:login')

jango_ui/blogs/templates/blogs/add_blog.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add new Blog</title>
</head>
<body>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Добавить новую запись">
</form>

</body>
</html>

jango_ui/blogs/templates/blogs/add_category.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add category</title>
</head>
<body>
<form action="{% url 'blogs:add_category' %}" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Добавить новую категорию">
</form>

</body>
</html>

jango_ui/blogs/templates/blogs/all_blogs.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <title>{{ Name }}</title>
    <style>
        {% include "blogs/styles.css" %}
    </style>
</head>

<body>
    <div class="wrapper" id="body"> </div>
<script>
var xhr = new XMLHttpRequest();
xhr.open('GET', "{{ url }}", false);
xhr.send();

if (xhr.status != 200) {
  document.getElementById("body").innerHTML = ( xhr.status + ': ' + xhr.statusText );
} else {
  let data_json = JSON.parse(xhr.responseText);

  let e = document.getElementById("body");

  data_json.forEach(b => e.innerHTML +=`
                    <div><header style="text-align:center;"><a href="/blog/${b.id}/"> ${b.name}</a></header>
                    <header><br/>Блог в категории:
                        <a href="/Categories/${b.category}/"> ${b.category} </a></br></header>
                    <br><main> ${b.text.substring(0,51)}</main><br>
                    <footer> Автор: <a href="/author/${b.author}/"> ${b.author}</a>
                    <br> Дата: ${b.date}</br></footer></div>`);
  }


</script>

<br><a href="{% url 'blogs:home_page' %}"><- Вернуться на главную страницу</a></br>

</body>
</html>

jango_ui/blogs/templates/blogs/blog.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ Name }}</title>
</head>
<body>
    <div id="body"> </div>
<script>
var xhr = new XMLHttpRequest();
xhr.open('GET', "{{ url }}", false);
xhr.send();

if (xhr.status != 200) {
  document.getElementById("body").innerHTML = ( xhr.status + ': ' + xhr.statusText );
} else {
  let b = JSON.parse(xhr.responseText);

  let e = document.getElementById("body");

  console.log(b)
  e.innerHTML +=`
                    <h1><a href="/blog/${b.id}/"> ${b.name}</a></h1>
                    <br><a href="{% url 'blogs:home_page' %}"><- Вернуться на главную страницу</a></br>
                    <h3><br/>Блог в категории:
                        <a href="/Categories/${b.category}/"> ${b.category} </a></br></h3>
                    <h3>${b.text}<h3>
                    <h3> Автор: <a href="/author/${b.author}/"> ${b.author}</a>
                    <br>Дата: ${b.date}</br></h3>`;
  }


</script>



</body>
</html>

jango_ui/blogs/templates/blogs/error.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Some error</title>
</head>
<body>
<h3>Запись автора {{ author }}</h3>
<h3>К сожалению у вас нет прав чтобы откредактировать данную запись</h3>
<h3><a href="{% url 'blogs:blogs_list' %}"><- Вернуться</a></h3>
</body>
</html>

jango_ui/blogs/templates/blogs/home_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home Page</title>
</head>
<body>
<h1> Добро пожаловать на главную страницу NEW BLOG!</h1>
<h2>Вы можете <a href="{% url 'users:login' %}">Войти</a> или <a href="{% url 'users:signup' %}">Зарегистрироваться</a></h2>
<a href="{% url 'blogs:blogs_list' %}">Просмотреть все записи</a>
</body>
</html>

jango_ui/blogs/templates/blogs/update_blog.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Update Blog</title>
</head>
<body>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Редактировать">
</form>
</body>
</html>

jango_ui/blogs/templates/blogs/user_home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>UserHome</title>
</head>
<body>
<h1> Добро пожаловать на домашнюю страницу {{ request.user.first_name }}!</h1>
<h2>Аккаунт пользователя: {{ request.user }}</h2>

<h4>Мои посты <a href="{% url 'blogs:author_blogs' name=request.user %}">  <input type="submit" value="Открыть"></a></h4>
<h4>Добавить новый пост <a href="{% url 'blogs:add_blog' %}">  <input type="submit" value="Добавить пост"></a></h4>
<h4>Добавить новую категорию <a href="{% url 'blogs:add_category' %}">  <input type="submit" value="Добавить категорию"></a></h4>
<h4>Выйти из учетной записи <a href="{% url 'users:logout' %}">  <input type="submit" value="Выйти"></a></h4>
</body>
</html>

jango_ui/users/templates/users/login.html
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
</head>
<body>
<h1> Пожалуйста, введите свой логин и пароль!</h1>
<hr>
<br><form action="{% url 'users:login' %}" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Войти">
</form></br></hr>
<br>Вернуться в главное меню  <a href="{% url 'blogs:home_page' %}"><input type="submit" value="Главное меню"></a></br>
</body>
</html>

jango_ui/users/templates/users/signup.html
<!DOCTYPE html>
<style>
input[type=text], select {
  width: 100%;
  padding: 12px 20px;
  margin: 8px 0;
  display: inline-block;
  border: 1px solid #ccc;
  border-radius: 4px;
  box-sizing: border-box;
}

input[type=submit] {
  width: 100%;
  background-color: #4CAF50;
  color: white;
  padding: 14px 20px;
  margin: 8px 0;
  border: none;
  border-radius: 4px;
  cursor: pointer;
}

input[type=submit]:hover {
  background-color: #45a049;
}

div {
  border-radius: 5px;
  background-color: #f2f2f2;
  padding: 20px;
}
</style>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Register</title>
</head>
<body>
<h2><hr>Форма регистрация нового пользователя</hr></h2>
<hr><form action="{% url 'users:signup' %}" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Зарегистрироваться">
</form></hr>
</body>
</html>